import { formatDate } from '../utils/helper/helpers';

export const TEXTS = {
  appName: 'Gov Built Mobile App',
  spalsh: {
    gov: 'Gov',
    builtPlateform: 'Built Platform',
    licensingSoftware: 'Permitting and Licensing Software',
    nextGeneration: 'for the Next Generation',
    CloudPermitting: 'Cloud Permitting | Licensing | Websites',
  },
  login: {
    email: 'Email or Username',
    emailPlaceholder: 'Enter your email and username',
    password: 'Password',
    passwordPlaceholder: 'Enter your password',
    title: 'Login',
    button: 'Login',
    forgotPassword: 'Forgot Your Password?',
    welcome: 'Welcome',
    validCityCountry: 'Select a valid site to proceed',
    validEmailPassword: 'Enter a valid email/username and password to proceed',
    selectCityCountry: 'Select City/County',
    requiredCityCountry: 'A Site must be selected before you can continue',
    selectSite: 'Select Your Site to Continue',
    selectSitePlaceholder: 'Start typing...',
  },
  offlineSync: {
    noInternet: 'No internet connection available.',
    SuccessMsg: 'All offline data synced successfully.',
    startSyncing: 'Sync Offline Changes to Server',
    tab: 'Tab',
    case: 'Case',
  },
  sideDrawerText: {
    myCase: 'My Cases',
    mySchedule: 'My Schedule',
    dailyInspections: 'Daily Inspections',
    licenses: 'My Licenses',
    parcels: 'Parcels',
    newForm: 'New Form',
    reports: 'Reports',
    formSubmissions: 'Form Submissions',
    deactivateBiometric: 'Deactivate biometric',
    activateBiometric: 'Activate biometric',
    appUpdateAvailable: 'App update available',
    logout: 'Logout',
  },
  biometric: {
    authenticateToContinue: 'Authenticate to continue',
    enterPIN: 'Enter PIN',
    biometricAuthentication: 'Biometric authentication not available or not set up on this device.',
    verifyIdentity: 'Verify your identity',
    usePasscode: 'Use Passcode',
    authenticationSuccessfully: 'Authentication Successfully',
    authenticationFailed: 'Authentication Failed',
    biometricNotAvailable: 'Biometric not available or not set up.',
    verificationFailed: 'Verification failed.',
    errorFetching: 'Error fetching tenant list:',
  },
  dashboard: {},
  home: {
    newAsgmts: 'New Asgmts',
    offlineItems: 'Offline Items',
    myCases: 'My Cases',
    todayAppts: "Today's Appts",
    mySchedule: 'My Schedule',
    dailyInspections: 'Daily Inspections',
    licenses: 'My Licenses',
    parcels: 'Parcels',
    newForm: 'New Form',
    reports: 'Reports',
    formSubmissions: 'Form Submissions',
  },
  alertMessages: {
    anotherUserLogin: 'Logging In with another user?',
    anotherUserLoginMsg:
      'All you previous data will be deleted, Are you sure? You want to login with different user?',
    teamMemberAlert:
      'Your user does not have a team member associated with it. Please, contact your admin to get a team member created.',
    accessMobileApplicationAlert: "You don't have access mobile application.",
    SelectEmailPassword: 'Please enter user email and password.',
    logoutAlert: 'Are you sure you want to logout?',
    cancel: 'Cancel',
    yes: 'Yes',
    confirm: 'Confirm',
    logout: 'Logout',
    enableBiometric: 'Enable biometric for a faster and more secure authentication',
    forgotPassOfflineMsg: 'No internet connection. You cannot reset your password in offline.',
    noPermissionAlertMessage: 'You do not have permission to access this area.',
    biometricLogin: 'Biometric Login',
    deactivateBiometric: 'Are you sure you want to deactivate biometric login?',
    activateBiometric: 'Are you sure you want to activate biometric login?',
    successfullyDeactivated: 'Successfully Deactivated',
    successfullyActivated: 'Successfully Activated',

    permissionRequired: 'Permission Required',
    UpdateAlert: 'Update Alert',
    UpdateMsg: 'New update is available. We recommend updating.',
    UpdateNewVersion: 'A newer version of the app is available.',
    updateNow: 'Update Now',
    updateLatter: 'Update Later',
    updateRequired: 'Update Required',
    mandatoryUpdateMes:
      'New mandatory update is available. Please update to continue using the app.',
    accessRestricted: 'Access Restricted',
    editCasePermission: 'You do not have access to edit this case.',
    noDataFound: 'No data found',
    TypeSearch: 'Type to search...',
    Retry: 'Retry',
    NewCaseAssignments: 'New Case Assignments From the Last Week',
    offlineMsg: "You're offline. My Schedule feature may not work.",
    success: 'Success',
    failed: 'Failed',
    dontHaveAction: "You don't have access to this.Please check your permissions and try again.",
    privateLicenseMsg:
      'The License has been marked as Private and you do not have access to it. Please ask a user that has access any questions.',
    privateCaseMsg:
      'The Case has been marked as Private and you do not have access to it. Please ask a user that has access any questions.',

    internetConnectionMsg:
      'Your internet connection is lost, and this item is not accessible offline. Please check your network connection and attempt the action again.',
    noNetwork: 'No internet connection. Sync will retry when online.',
    offlineSaveDataError:
      'Your internet connection is lost, and this item is not accessible offline. Please check your network connection and attempt the action again.',
    offlineSaveDataMsg:
      'The item was saved offline due to no internet connection. Make sure to open app when you have an internet connection to sync.',
    licenseAssignTeamMember:
      'You are not an assigned team member. If you save you will not be able to see this license. Are you sure you want to continue?',
    caseAssignTeamMember:
      'You are not an assigned team member. If you save you will not be able to see this case. Are you sure you want to continue?',
    dontAction: "You don't have access to this.",
    notAvailableInOffline: 'This item is not accessible in offline mode',
  },
  errors: {
    noInternet: 'No internet connection',
    unknown: 'Something went wrong',
  },
  caseScreen: {
    heading: 'My Cases',
    allCases: 'Show All',
    caseType: 'Case Type',
    caseTypePlaceholder: 'Select a case type...',
    address: 'Address',
    publish: 'Publish',
    published: 'Published',
    draft: 'Draft',
    editCaseHeading: 'Edit Case',
    createBy: 'Created By : ',
    editedBy: 'Edited By : ',
    casUniqueNumber: 'Case #',
    private: 'Private',
    caseNumberDetails: 'Case Number Details',
    caseNumberDetailsPlaceholder: 'Enter case number detail',
    caseName: 'Case Name',
    caseNamePlaceholder: 'Enter case name',
    status: 'Case Status',
    statusPlaceholder: 'Select a case status...',
    billingStatus: 'Billing Status',
    billingStatusPlaceholder: 'Select a billing status...',
    caseTag: 'Case Tag',
    caseTagPlaceholder: 'Select a case tag...',
    caseSubType: 'Case Sub Type',
    caseSubTypePlaceholder: 'Select cases sub type...',
    totalCost: 'Total Cost',
    totalCostPlaceholder: 'Enter total cost',
    aptste: 'Apt/Ste',
    aptstePlaceholder: 'Enter Apt/Ste',
    parcelNumber: 'Parcel Number',
    parcelNumberPlaceholder: 'Enter parcel number',
    quickReference: 'Quick Reference',
    quickReferencePlaceholder: 'Enter quick ref number text',
    description: 'Description',
    descriptionPlaceholder: 'Type your description here...',
    advancedForm: 'Advanced Form',
    teamMember: 'Team Member',
    shortBy: 'Sort By',
    createdDate: 'Created Date',
    close: 'Close',
    noCasemsg: 'No Case Available.',
    allowAssigned: 'Only Allow Assigned Team Members to View',
    updateCaseSuccessMsg: 'The case information has been successfully updated.',
    updateLicenseSuccessMsg: 'The license information has been successfully updated.',
  },
  advanceFilter: {
    advancedFiltersTitle: 'Advanced Filters',
    filterTypeLabel: 'Filter Type',
    caseTypeLabel: 'Case Type',
    caseStatusLabel: 'Case Status',
    caseSubTypeLabel: 'Case Sub Type',
    attachedAdvanceFormLabel: 'Attached Advance Form',
    teamMemberLabel: 'Team Member',
    caseTag: 'Case Tag',
    sortBy: 'Sort By',
    close: 'Close',
    filter: 'Filter',
    licenseRenewalStatusLabel: 'License Renewal Status',
    licenseType: 'License Type',
    licenseSubTypeLabel: 'License Sub Type',
    licenseStatusLabel: 'License Status',
    licenseTag: 'License Tag',
    advancedFilters: 'Advanced Filters',
    searchHere: 'Search here...',
  },
  subScreens: {
    setting: {
      heading: 'Settings',
      permitIssuedDate: 'Permit Issued Date',
      permitIssueHints: 'The permit issued date of the case.',
      permitExpirationDate: 'Permit Expiration Date',
      permitExpirationHints: 'The permit expiration date of the case.',
      viewOnlyAssignUsers: 'Only Allow Assigned Users to View',
      assignedTeamMember: 'Assign Team Members',
      assignedTeammenberPlaceholder: 'Select Team Members',
      assignedTeamHint: 'Will show only username assigned team members.',

      assignAccess: 'Assign Access',
      projectValuation: 'Project Valuation',
      projectValuationPlaceholder: 'Enter project valuation',
      projectValuationHints: 'The Project Valuation of the case.',
      caseOwner: 'Case Owner',
      caseOwnerPlaceholder: 'Search case owner...',
      save: 'Save',
      saving: 'Saving...',
      loading: 'Loading...',
      updateSuccess: 'Settings updated successfully',
      updateError: 'Failed to update settings. Please try again.',
      fetchError: 'Failed to fetch settings. Please try again.',
      userValidation: 'Please select at least one assigned user.',
      accessValidation: 'Please select assign access.',
      dateValidation: 'Issued date cannot be later than expiration date.',
      noSettingsFound: 'No settings found for this item.',
    },
    adminNotes: {
      heading: 'Admin Notes',
      public: 'Public',
      notePlaceholder: 'Type your note here...',
      noComments: 'No comments available',
      setAlert: 'Set as Alert',
      makePublic: 'Make Public',
      fillComment: 'Please enter a comment',
      commentError: 'Failed to save comment',
      commentUpdateError: 'Failed to save comment',
      commentUpdated: 'Comment updated successfully',
      moderatorComment: 'Comment removed by moderator',
    },
    commentWithFileAttached: {
      title: 'Comment',
      selectedFiles: 'Selected Files',
      unsavedChangesTitle: 'Unsaved Changes',
      unsavedChangesMessage:
        'You have unsaved changes. Are you sure you want to discard them and leave?',
      cancel: 'Cancel',
      discard: 'Discard',
      commentValidation: 'Please enter a comment before saving.',
      saveSuccess: 'Comment saved successfully!',
      savingError: 'Failed to save comment. Please try again.',
      offlineSaveSuccess: 'Comment saved offline successfully!',
      selectDocumentTitle: 'Select Document',
      camera: 'Camera',
      photosLibrary: 'Photos Library',
      folder: 'Folder',
      fileSelectedSuccess: 'File(s) selected successfully!',
      fileSelectionError: 'Failed to select file. Please try again.',
      cameraPermissionDenied: 'Permission to access the camera is required!',
      mediaPermissionDenied: 'Permission to access the media library is required!',
      invalidFile: 'The file with extension',
      invalidSelection: 'The following files have unsupported extensions and were not uploaded:',
    },
    attachedItem: {
      heading: 'Attached Items',
      noItems: 'No Attached found',
      addItem: 'Add Item',
      itemName: 'Item Name',
      itemNamePlaceholder: 'Enter item name',
      itemDescription: 'Item Description',
      itemDescriptionPlaceholder: 'Enter item description',
      uploadFile: 'Upload File',
      fileUploadError: 'Failed to upload file',
      fileUploadSuccess: 'File uploaded successfully',
      onlineAttchedItems: 'This Attach item not available in offline mode.',
      selectFile: 'Select Folder or File',
      selectForm: 'Select form',
      noFormsAvailable: 'No forms available',
    },
    contactAndContract: {
      contactHeading: 'Contact',
      contractorHeading: 'Contractor',
      contactName: 'Contact Name',
      nameValidation: 'Please fill the first name',
      emailValidated: 'Please Enter the valid email Format',
      savingError: 'Something went wrong while saving the data. Please try again',
      firstName: 'First Name',
      firstNamePlaceholder: 'Enter first name',
      lastName: 'Last Name',
      lastNamePlaceholder: 'Enter last name',
      phoneNumber: 'Phone Number',
      phoneNumberPlaceholder: 'Enter phone number',
      email: 'Email',
      emailPlaceholder: 'Enter email',
      mailingAddress: 'Mailing Address',
      mailingAddressPlaceholder: 'Enter mailing address',
      contactType: 'Contact Type',
      contactTypePlaceholder: 'Select contact type...',
      businessName: 'Business Name',
      businessNamePlaceholder: 'Enter business name',
      isAllowAccess: 'Allow Access',
      isAllowAccessPlaceholder:
        'The User have ability to see case, permit types, form letters on FE',
      isPrimary: 'Is Primary',
      isPrimaryPlaceholder: 'Select if this is a primary contact',
      notes: 'Notes',
      notesPlaceholder: 'Enter notes',
      endDate: 'End Date',
      endDatePlaceholder: 'Select end date',
      addNew: 'Case Contact',
      addNewLicense: 'License Contact',
      update: 'Update Contact',
      licenseType: 'License Type',
      licenseTypePlaceholder: 'Select license type...',
      license: 'License',
      licensePlaceholder: 'Select license...',
      noContactFound: 'No contact found',
      noContractorFound: 'No contractor found',
      contractName: 'Contract Name',
      contractNamePlaceholder: 'Enter contract name',
      licenseValidate: 'Please select license type and license.',
      saveSuccess: 'Contact saved successfully',
      failedToFetchCommand: 'Failed to fetch comments: Invalid response status',
      failedToSaveCommand: 'Failed to save comment',
    },
    publicComment: {
      heading: 'Public Comments',
    },
    location: {
      heading: 'Location',
      parcelIdLabel: 'Parcel Id',
      addressLabel: 'Address',
      googlePlacesPlaceholder: 'Enter a location',
      endDateLabel: 'End Date',
      latitudeLabel: 'Latitude',
      longitudeLabel: 'Longitude',
      manualLocationLabel: 'Set Manual Location',
      addLocation: 'Add Location',
      submitButton: {
        publish: 'Publish',
        update: 'Update',
      },
      editButton: 'Edit',
      deleteDialog: {
        title: 'Delete Multi Location',
        description: 'Are you sure you want to delete this parcel location',
      },
      addressRequired: 'Address is required',
    },
    statusChangeLog: {
      heading: 'Logs',
      dateLabel: 'Date',
      userNameLabel: 'User Name',
      previousStatusLabel: 'Previous Status',
      statusLabel: 'Status',
    },
    inspectionLog: {
      heading: 'Inspection Log',
      dateLabel: 'Date',
      userNameLabel: 'User Name',
      typeLabel: 'Type',
      inspectorLabel: 'Inspector',
      inspectionTypeLabel: 'Inspection Type',
      statusLabel: 'Status',
      appointmentDateLabel: 'Appointment Date',
    },
    teamChangeLog: {
      heading: 'Team Change Log',
      dateLabel: 'Date',
      publishedByLabel: 'Published By',
      previousTeamMembersLabel: 'Previous Team Members',
      teamMembersLabel: 'Team Members',
    },
    accountingLog: {
      heading: 'Accounting Log',
      dateLabel: 'Date',
      userNameLabel: 'User Name',
      accountingDetailLabel: 'Accounting Detail',
      statusLabel: 'Status',
      totalCostLabel: 'Total Cost',
      paidAmountLabel: 'Paid Amount',
      noteLabel: 'Note',
    },
    taskChangeLog: {
      heading: 'Task Change Log',
      dateLabel: 'Date',
      taskLabel: 'Task',
      userNameLabel: 'User Name',
      previousStatusLabel: 'Previous Status',
      statusLabel: 'Status',
    },
    payment: {
      heading: 'Payments',
    },
    related: {
      heading: 'Related',
      parent: 'Parent',
      child: 'Children',
    },
    subLicense: {
      heading: 'Sub License',
    },
    licenseDetails: {
      testScore: 'Test Score',
      testScoreHints: 'The Test Score for the License.',
      testScorePlaceholder: 'Enter test score',
      licenseFee: 'License Fee',
      licenseFeeHints: 'The License Fee of the License.',
      licenseFeePlaceholder: 'Enter license fee',
      liabilityInsuranceExpirationDate: 'Liability Insurance Expiration Date',
      liabilityInsuranceExpirationDateHint:
        'The Liability Insurance Expiration Date of the License.',
      workerCompInsuranceExpirationDate: "Worker's Comp Insurance Expiration Date",
      workerCompInsuranceExpirationDateHint: "The Expiration Date for Worker's Comp Insurance.",
      issueDate: 'Issue Date',
      issueDateHint: 'The Issue Date for the License.',
      effectiveDate: 'Effective Date',
      effectiveDateHint: 'The Effective Date for the License.',
      assignTeamMembers: 'Assign Team Members',
      teamMemberPlaceholder: 'Select a assigned team members',
      teamMemberHint: 'The Assigned Users of the form.',
      onlyAllowAssignedTeamMembersView: 'Only Allow Assigned Team Members to View',
      licenseOwner: 'License Owner',
      licenseOwnerPlaceholder: 'Enter license owner',
      publish: 'Publish',
      saveSuccess: 'License details submitted successfully',
    },
    owner: {
      owner: 'Owner',
      name: 'Name',
      nameHint: 'The Name of the owner.',
      email: 'Email',
      emailHint: 'The Email of the owner.',
      phoneNumber: 'Phone Number',
      phoneNumberHint: 'The Phone Number of the owner.',
      cellNumber: 'Cell Phone',
      cellNumberHint: 'The Cell Phone of the owner.',
      address: 'Address',
      addressHint: 'The Address of the owner.',
      mailingAddress: 'Mailing Address',
      mailingAddressHint: 'The Mailing Address of the owner.',
      saveSuccess: 'Owner details submitted successfully',
    },
    sendEmail: {
      heading: 'Sent Emails',
    },
    task: {
      heading: 'Tasks',
      teamMemberLabel: 'Team Member',
      statusLabel: 'Status',
      typeLabel: 'Type',
      dueDateLabel: 'Due Date',
      statusChangeDateLabel: 'Status Change Date',
    },
    accountingDetails: {
      heading: 'Accounting Details',
      accountingDetailLabel: 'Accounting Detail',
      totalCostLabel: 'Total Cost',
      paidAmountLabel: 'Paid Amount',
      dueAmountLabel: 'Due Amount',
      statusLabel: 'Status',
      noteLabel: 'Note',
      createdOnLabel: 'Created On',
      modifiedOnLabel: 'Modified On',
      paidOnLabel: 'Paid On',
      createdByLabel: 'Created By',
      modifiedByLabel: 'Modified By',
      paymentByLabel: 'Payment By',
      expandButton: {
        showMore: 'View More ▼',
        hideDetails: 'Hide Details ▲',
      },
    },
    advanceFormSubmission: {
      heading: 'Submissions',
      formLabel: 'Form Type',
      statusLabel: 'Status',
      dateLabel: 'Modified Date',
      authorLabel: 'Author',
      placeholder: {
        search: 'Search submissions',
        dropdown: 'All Advanced Form Status',
      },
      switchLabel: 'All Submissions',
    },
    filePicker: {
      dialog: {
        title: 'Select Document Source',
        photos: 'Photos Library',
        folder: 'Folder',
        camera: 'Camera',
        cancel: 'Cancel',
      },
      errors: {
        cameraPermission: "You've refused to allow this app to access your camera!",
        mediaPermission: 'Permission to access the media library is required!',
        invalidFile: 'The file with extension {extension} is not allowed to be uploaded.',
        invalidSelection:
          'The following files have unsupported extensions and were not uploaded: {files}',
        pickerCancelled: 'File selection was cancelled.',
      },
    },
    dailyInspection: {
      heading: 'Daily Inspections',
      subjectLabel: 'Subject',
      addressLabel: 'Address',
      inspectionDateLabel: 'Inspection Date',
      chooseInspector: 'Filter by Inspector',
      advancedFilters: 'Advanced Filters',
      createRoute: 'Create Route',
      downloadCSV: 'Download CSV',
      updateOrder: 'Update Order',
      dateRangePlaceholder: (start: string, end: string) =>
        `${formatDate(start, 'MM/DD/YYYY')} - ${formatDate(end, 'MM/DD/YYYY')}`,
      deleteDialog: {
        title: 'Delete Inspection',
        description: 'Are you sure you want to delete this inspection?',
      },
    },
    editInspection: {
      heading: 'Schedule Inspection',
      inspectionByLabel: 'Inspection By',
      statusLabel: 'Status',
      inspectionDateLabel: 'Inspection Date',
      preferredTimeLabel: 'Preferred Time',
      startTimeLabel: 'Start Time',
      endTimeLabel: 'End Time',
      saveButton: 'Save',
    },
    routeScreen: {
      heading: 'Daily Route',
    },
    parcel: {
      heading: 'Parcels',
      caseHeading: 'Case Parcels',
      submissionsHeading: 'Submission Parcels',
      childParcelHeading: 'Child Parcels',
      detailHeading: 'Parcel Details',
      parcelNumberLabel: 'Parcel Number',
      addressLabel: 'Address',
      ownerNameLabel: 'Owner Name',
      yearBuiltLabel: 'Year Built',
      parentParcelLabel: 'Parent Parcel',
      propertyTypeLabel: 'Property Type',
      marketValueLabel: 'Current Market Value',
      tenantNameLabel: 'Current Tenant Name',
      descriptionLabel: 'Parcel Description',
      submittedByLabel: 'Submitted By',
      createdDateLabel: 'Created Date',
      parcelNumberPlaceholder: 'Enter Parcel Number',
      addressPlaceholder: 'Enter Address',
      searchButton: 'Search',
      detailTab: 'Parcel Details',
      caseTab: 'Case',
      submissionsTab: 'Submissions',
      childParcelsTab: 'Child Parcels',
    },
    parcelLocation: {
      heading: 'Locations',
      parcelIdLabel: 'Parcel ID',
      addressLabel: 'Address',
      endDateLabel: 'End Date',
      latitudeLabel: 'Latitude',
      longitudeLabel: 'Longitude',
      googlePlacesPlaceholder: 'Enter address',
      submitButton: {
        update: 'Update',
      },
      deleteDialog: {
        title: 'Delete Location',
        description: 'Are you sure you want to delete location',
      },
    },
    schedule: {
      heading: 'My Schedule',
      startDateLabel: 'Start Date',
      endDateLabel: 'End Date',
      filterButton: 'Filter',
    },
  },
  license: {
    license: 'My Licenses',
    licenseEdit: 'License Edit',
    noLicensemsg: 'No License Available.',
    // Edit license
    licenseUniqueNumber: 'License #',
    licenseDescripter: 'License Descriptor',
    // Edit screen placeholder text
    enterLicenseDescripter: 'Enter license descriptor',
    firstName: 'Applicant First Name',
    firstNamePlaceholder: 'Enter applicant first name',
    applicantLastName: 'Applicant Last Name',
    applicantLastNamePlaceholder: 'Enter Applicant last name',
    businessName: 'Business Name',
    businessNamePlaceholder: 'Enter business name',
    phoneNumber: 'Phone Number',
    phoneNumberPlaceholder: 'Enter phone number',
    cellNumber: 'Cell Number',
    cellNumberPlaceholder: 'Enter cell number',
    email: 'Email',
    emailPlaceholder: 'Enter email address',
    expirationDate: 'Expiration Date',
    status: 'Status',
    statusPlaceholder: 'Select a license status',
    renewalStatus: 'Renewal Status',
    renewalStatusPlaceholder: 'Select a renewal status',
    licenseType: 'License Type',
    licenseTypePlaceholder: 'Select a license type',
    licenseSubType: 'License Sub Types',
    licenseSubTypePlaceholder: 'Select license sub type',
    licenseTag: 'License Tags',
    licenseTagPlaceholder: 'Select a license tag',
    licenseLocation: 'license Location',
    licenseLocationPlaceholder: 'Select a license location',
    parcelNumber: 'Parcel Number',
    parcelNumberPlaceholder: 'Enter parcel number',
    quickReference: 'Quick Reference',
    quickReferencePlaceholder: 'Enter quick ref number text',
    description: 'Additional Info',
    descriptionPlaceholder: 'Type your additional information here...',
    teamMember: 'Assigned Team Members',
    teamMemberPlaceholder: 'Select a assigned team members',
    paymentReceived: 'Payment Received',
    paymentReceivedPlaceholder: 'Select a payment received type',
    allowAssigned: 'Only Allow Assigned Team Members to View',
    updateLicenseSuccessMsg: 'The license information has been successfully updated.',
    licenseTypes: 'License Type',
    // Validation
    licenseNumberValidation: 'Please enter licence number.',
    applicantFirstNameValidation: 'The applicant first name is required.',
    applicantLastNameValidation: 'The applicant Last Name is required.',
    applicantEmailValidation: 'The email is required.',
    invalidEmailValidation: 'Enter a valid email address.',
    licenseStatusValidation: 'The license status is required.',
    licenseTypeValidation: 'The license type is required.',
    licenseLocationValidation: 'The location is required.',
    licenseApprovedUntilPaymentReceived: "The license doesn't approved until payment received.",
    licenseTeamMemberValidation: 'The case assign team members field is required.',
    private: 'Private',
  },
  validationMsg: {
    emailIsRequired: 'Email is required.',
    emailIsInvalid: 'Enter a valid email address.',
  },
  newForm: {
    noNewFormMsg: 'No New Form Available.',
    newFormText: 'New Form',
    placeholderText: 'Type to search',
  },
  apiServiceFile: {
    badRequest: 'Bad request',
    notHavePermission: 'You do not have permission to access this content.',
    internalServerError: 'Internal server error. Try again later.',
    networkIssue: 'Network issue. Please check your internet connection.',
    unexpectedErrorOccurred: 'Unexpected error occurred. Please try again.',
    noOfflineDataFound: 'No offline data found. Please login online first.',
    invalidCredentials: 'Invalid credentials for offline login.',
    unableUserRole: 'Unable to fetch user role',
    invalidLoginCredentials: 'Invalid login credentials',
    loginFailedAlert: 'Login failed. Please try again.',
    somethingWentWrong: 'Something went wrong',
    loginSetupFailed: 'Login session setup failed',
    notFound: 'Content not found',
  },
};
