const IMAGES = {
  LOGO: require('../assets/images/logo.png'),
  BACKGROUND_IMAGE: require('../assets/images/ic_top_background_image.png'),
  LOGO_TEXT: require('../assets/images/ic_logo_text.png'),
  CIRCLE_IMAGE: require('../assets/images/ic_circle.png'),
  CIRCLE_ACTIVE_IMAGE: require('../assets/images/ic_circle_active.png'),
  RIGHT_ARROW: require('../assets/images/ic_right_arrow_new.png'),
  TOGGLE_DRAWER: require('../assets/images/ic_toggle.png'),
  FILTER_ICON: require('../assets/images/filter_icon.png'),
  CROSS_ICON: require('../assets/images/close_icon.png'),
  SEARCH_ICON: require('../assets/images/ic_search_icon.png'),
  EDIT_ICON: require('../assets/images/edit_icon.png'),
  EDIT_PENCIL_ICON: require('../assets/images/ic_edit_pencil.png'),
  DELETE: require('../assets/images/trash.png'),
  FLAG_ICON: require('../assets/images/flag_back.png'),
  PLAY_ICON: require('../assets/images/play_gray.png'),
  CALENDER_ICON: require('../assets/images/ic_calendar.png'),
  CLOCK_ICON: require('../assets/images/ic_time.png'),
  FORWARD_ICON: require('../assets/images/ic_right_gray.png'),
  PERSON_ICON: require('../assets/images/ic_person.png'),
  ATTACHMENT_ICON: require('../assets/images/ic_attachment.png'),
  CHAT_ICON: require('../assets/images/ic_chat.png'),
  SEND_ICON: require('../assets/images/ic_sent.png'),
  CLOSE_ICON: require('../assets/images/close.png'),
  PLUS_ICON: require('../assets/images/ic_plus.png'),
  PHONE_ICON: require('../assets/images/telephone.png'),
  EMAIL_ICON: require('../assets/images/mail.png'),
  LOCATION_ICON: require('../assets/images/location.png'),
  SHARE_ICON: require('../assets/images/ic_share.png'),
  REFRESH_ICON: require('../assets/images/ic_refresh.png'),
  DOWNLOAD_ICON: require('../assets/images/download.png'),
  ADD_FILE: require('../assets/images/add_new_file.png'),
  COLLAPSE_ICON: require('../assets/images/ic_arrow.png'),
  EXPAND_ICON: require('../assets/images/up-arrow.png'),
  BIOMATRIX_ICON: require('../assets/images/icon_biomatrices.png'),
  // Custom header
  LEFT_ARRAOW: require('../assets/images/ic_left_arrow.png'),
  BACKGROUND_IMAGE_TOP: require('../assets/images/ic_top_background_image.png'),
  HEADER_BACKGROUND: require('../assets/images/ic_header_bg.png'),

  // HOME FRAME BG
  ASSIGNEMENT_BG: require('../assets/images/homeCard/bgAssignmentImage.png'),
  OFFLINE_BG: require('../assets/images/homeCard/bgOfflineItemsImage.png'),
  MYCASE_BG: require('../assets/images/homeCard/bgMyCaseImage.png'),
  DAILYAPPOINTMENT_BG: require('../assets/images/homeCard/bgAppointmentsImage.png'),
  // Home screen IMAGES
  MY_SHEDULE: require('../assets/images/ic_my_schedule.png'),
  DAILY_ROUTE: require('../assets/images/ic_daily_route.png'),
  MY_CASE: require('../assets/images/ic_my_case.png'),
  LICENSE: require('../assets/images/ic_licenses.png'),
  PARCELS: require('../assets/images/ic_parcels.png'),
  NEW_FORM: require('../assets/images/ic_new_form.png'),
  FORM_SUBMISSION: require('../assets/images/ic_sub_list.png'),

  // Side drawer images
  HOME_LOGO: require('../assets/images/ic_sidebar_home.png'),
  DRAWER_LOGO: require('../assets/images/ic_logo_text.png'),
  DRAWER_MYCASE: require('../assets/images/ic_sidebar_mycase.png'),
  DRAWER_MY_SCHEDULE: require('../assets/images/ic_sidebar_myschedule.png'),
  DRAWER_DAILY_INSPECTION: require('../assets/images/ic_daily_route.png'),
  DRAWER_LICENSE: require('../assets/images/ic_sidebar_license.png'),
  DRAWER_PARCELS: require('../assets/images/ic_sidebar_parcels.png'),
  DRAWER_NEW_FORM: require('../assets/images/ic_sidebar_newform.png'),
  DRAWER_REPORTS: require('../assets/images/ic_reports.png'),
  DRAWER_FORM_SUBMISSION: require('../assets/images/ic_sub_list.png'),
  DRAWER_BIOMETRIC: require('../assets/images/icon_side_nav_bio.png'),
  DRAWER_APP_UPDATE: require('../assets/images/ic_mobile_sync.png'),
  LOGOUT: require('../assets/images/ic_logout.png'),
  // ADD_FORM_ICON: require("../assets/images/ic_add_form.png"),
  NO_DATA: require('../assets/images/NoData.png'),

  ARROW_UP: require('../assets/images/ic_expand_arrow.png'),
  ARROW_DOWN: require('../assets/images/ic_color_arrow.png'),
  // ic_left_arrow: require('../assets/images/ic_left_arrow.png'),
  // ic_download_2: require('../assets/images/ic_download_2.png'),
  // ic_edit_pencil: require('../assets/images/ic_edit_pencil.png'),
  // ic_delete: require('../assets/images/ic_delete.png'),
  // ic_folder: require('../assets/images/ic_folder.png'),
  // ic_pdf: require('../assets/images/ic_pdf.png'),
  // ic_xls: require('../assets/images/ic_xls.png'),
  // ic_ppt: require('../assets/images/ic_ppt.png'),
  // ic_psd: require('../assets/images/ic_psd.png'),
  // ic_doc: require('../assets/images/ic_doc.png'),
  // ic_gallery: require('../assets/images/ic_gallery.png'),
  // ic_grid_icon: require('../assets/images/ic_grid_icon.png'),
  // ic_list_icon: require('../assets/images/ic_list_icon.png'),
  // ic_add_file: require('../assets/images/add_file.png'),
  // ic_add_folder: require('../assets/images/add_folder.png'),
  // ic_menu_new: require('../assets/images/ic_menu_new.png'),
  // ic_edit: require('../assets/images/ic_edit.png'),
  // ic_top_background_image: require('../assets/images/ic_top_background_image.png'),
};
export default IMAGES;
